version: '3'

services:

  openapi-golang:
    container_name: openapi-golang
    image: golang:1.21.6-alpine3.19
    tty: true
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: /bin/sh -c "go install github.com/cosmtrek/air@latest && air"
    volumes:
      - ./app:/usr/src/app

  openapi-db:
    image: postgres:16.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.2
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin