version: '3'

services:

  openapi-golang:
    container_name: openapi-golang
    image: golang:1.21.6-alpine3.19
    tty: true
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: /bin/sh -c "go install github.com/cosmtrek/air@latest && air"
    volumes:
      - ./app:/usr/src/app
