// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	InboundItem string
	StockItem   string
}{
	InboundItem: "inbound_item",
	StockItem:   "stock_item",
}
