openapi: 3.0.3
info:
  title: Stock Item API
  version: 1.0.0
paths:
  /stock/items:
    post:
      summary: Create Stock Item
      description: Create Stock Item
      operationId: PostStockItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minimum: 1
                  maximum: 100  
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /stock/items/{id}:
    put:
      summary: Update Stock Item
      description: Update Stock Item
      operationId: PutStockItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minimum: 1
                  maximum: 100  
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    OK:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StockItem"
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StockItem"
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestResponse"
    InternalServerError:
      description: Internal Server Error
  schemas:
    BadRequestResponse:
      type: array
      items:
        type: object
        properties:
          message:
            type: string
    StockItem:
      type: object
      required:
        - id
        - name
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time